### ISSUE TITLE
linkedlist? warum? 

### ISSUE THREAD

**Issue by ullenboom** [EarlGreyT/date4u#2]
https://github.com/EarlGreyT/date4u/blob/d5cb2df077f78393ab0eac97a7235a4eea7d53d4/src/main/java/de/earlgreyt/date4u/core/formdata/ProfileFormData.java#L25

und wenn dann links nur referenztyp List

**Comment by EarlGreyT** [comment]
7318f54eba814dd01a7b2d6674a516e3a3b6213e

vermutlich koffein-entzug
