### ISSUE TITLE
warum nicht gleich ALL? refresh mitzunehmen ist ja auch ok, oder?

### ISSUE THREAD

**Issue by ullenboom** [EarlGreyT/date4u#3]
https://github.com/EarlGreyT/date4u/blob/d5cb2df077f78393ab0eac97a7235a4eea7d53d4/src/main/java/de/earlgreyt/date4u/core/entitybeans/Profile.java#L50

**Comment by EarlGreyT** [comment]
Ich hatte gelesen, dass DELETE probleme macht auf Many-To-Many-Relationen zwischen gleichen Typen. und hatte angst das ich aussversehen ganze profile lösche, wenn ich ein like entferne.
Werd aufjedenfall noch schauen ob das passiert :)

**Comment by ullenboom** [comment]
guter punkt, recherchiere das mal.

**Comment by EarlGreyT** [comment]
https://thorben-janssen.com/avoid-cascadetype-delete-many-assocations/#Problems_with_CascadeTypeREMOVE_for_To-Many_Associations das war der Artikel den ich dazu gelesen hatte. Ich schätze beim like entfernen wäre noch alles ok, aber wenn ich ein Profil löschen würde könnte was schief gehen. Ich teste das Mal morgen.
