### ISSUE TITLE
das kann man kompakter schreiben: wenn nicht da, dann exception

### ISSUE THREAD

**Issue by ullenboom** [EarlGreyT/date4u#5]
https://github.com/EarlGreyT/date4u/blob/7318f54eba814dd01a7b2d6674a516e3a3b6213e/src/main/java/de/earlgreyt/date4u/core/UnicornDetailService.java#L23

**Comment by EarlGreyT** [comment]
5aea2939774dfc5e6f2c8fc2cd7755bf90732815

Danke, Ich muss mich noch mehr mit der Optional-API beschäftigen, da gibts bestimmt noch viele Stellen, die bescheuert sind.
